apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.containername }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.deployment.containername }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $k, $v := .Values.ports }}
            - name: {{ $k }}
              containerPort: {{ $v }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end}}
          {{- if .Values.env }}
          env: 
          {{- range $e, $f := .Values.env }}
            - name: {{ $e }}
              value: {{ $f }}
          {{- else }}
            []
          {{- end }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.envFrom}}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 10 }}
          {{- end }}
          {{- if .Values.volumes }}
          volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: {{ .Values.volumeMounts.mountPath}}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.volumes }}
      volumes:
        - {{- toYaml .Values.volumes | nindent 10 }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.image.secrets}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 6 }}
  {{- end }}