{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  name: {{ .Values.service.servicename }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.serviceport }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: {{ .Values.service.servicename }}
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}